//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.05 at 01:36:02 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.example.com/paymentOrder", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.service.paymentorder;
